export enum ConfigKey {
  // Twitch
  TWITCH_USERNAME = 'TWITCH_USERNAME',
  TWITCH_TOKEN = 'TWITCH_TOKEN',

  // Database
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
}
